# Energia gazdálkodás optimalizálása Spark használatával

MySql adatbázisban gyűjtünk adatokat rendszerünk fogyasztásáról, a rendelkezésre álló napelemek termeléséről, illetve az energia ár alakulásáról 15 perces felbontásban.

Az árakat a hupx oldalról API-n keresztül szereztük.

A fogyasztás, termelés és ár adatok rendre a **consumer_profile**, **solar_panel_production** és **hupx_energy_price** táblákban kerülnek letárolásra időbélyeggel együt.

In [2]:
import findspark
import pyspark.sql
from pyspark.sql import SparkSession
from pyspark.sql.functions import to_timestamp, col, to_utc_timestamp, count, monotonically_increasing_id


findspark.init()

spark = SparkSession.builder \
    .appName("PySpark MySQL Connection") \
    .getOrCreate()

24/05/18 14:45:01 WARN Utils: Your hostname, PySpark resolves to a loopback address: 127.0.1.1; using 192.168.64.129 instead (on interface ens33)
24/05/18 14:45:01 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address

:: loading settings :: url = jar:file:/home/student/.local/lib/python3.10/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml

Ivy Default Cache set to: /home/student/.ivy2/cache
The jars for the packages stored in: /home/student/.ivy2/jars
org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-d7943cf2-e764-409b-9a78-d21c79746c00;1.0
	confs: [default]
	found org.apache.spark#spark-sql-kafka-0-10_2.12;3.3.1 in central
	found org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.3.1 in central
	found org.apache.kafka#kafka-clients;2.8.1 in central
	found org.lz4#lz4-java;1.8.0 in central
	found org.xerial.snappy#snappy-java;1.1.8.4 in central
	found org.slf4j#slf4j-api;1.7.32 in central
	found org.apache.hadoop#hadoop-client-runtime;3.3.2 in central
	found org.spark-project.spark#unused;1.0.0 in central
	found org.apache.hadoop#hadoop-client-api;3.3.2 in central
	found commons-logging#commons-logging;1.1.3 in central
	found com.google.code.findbugs#jsr305;3.0.0 in central
	found org.apache.commons#commons-pool2;2.11.1 in central
:: resolution report :: resolve 2506ms :: artifacts dl 151ms
	:: modules in use:
	com.google.code.findbugs#jsr305;3.0.0 from central in [default]
	commons-logging#commons-logging;1.1.3 from central in [default]
	org.apache.commons#commons-pool2;2.11.1 from central in [default]
	org.apache.hadoop#hadoop-client-api;3.3.2 from central in [default]
	org.apache.hadoop#hadoop-client-runtime;3.3.2 from central in [default]
	org.apache.kafka#kafka-clients;2.8.1 from central in [default]
	org.apache.spark#spark-sql-kafka-0-10_2.12;3.3.1 from central in [default]
	org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.3.1 from central in [default]
	org.lz4#lz4-java;1.8.0 from central in [default]
	org.slf4j#slf4j-api;1.7.32 from central in [default]
	org.spark-project.spark#unused;1.0.0 from central in [default]
	org.xerial.snappy#snappy-java;1.1.8.4 from central in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   12  |   0   |   0   |   0   ||   12  |   0   |
	---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent-d7943cf2-e764-409b-9a78-d21c79746c00
	confs: [default]
	0 artifacts copied, 12 already retrieved (0kB/46ms)
24/05/18 14:45:06 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).

# Manuális ETL
Ez a blokk tesztadatok manuális betöltését szolgálja fáljokból, valamint egyéb kiegészítő adatok szolgáltatását, ha szükséges.

Itt kell elvégezni az adatok transzformálását, (pl: megfelelő típusra való cast-olás).

A következő blokkok futtatása kihagyható, ha nincsenek ilyen igények.

# Kiolvasás

In [28]:

#reading and transforming csv input, only run this block when needed.
consumption = spark.read.format("csv")\
          .option("header","true")\
          .option("delimiter",";")\
          .option("inferSchema","true")\
          .load("../ingest/consumption_profile.csv")

production = spark.read.format("csv")\
          .option("header","true")\
          .option("delimiter",",")\
          .option("inferSchema","true")\
          .load("../ingest/production_profile.csv")

price = spark.read.format("csv")\
          .option("header","true")\
          .option("delimiter",";")\
          .option("inferSchema","true")\
          .load("../ingest/price.csv")

consumption.show()
production.show(100)
price.show()

+----------+-------------------+--------+
|     Dátum|         Negyedórák| Group#4|
+----------+-------------------+--------+
|2022.01.01|2024-05-18 00:00:00|0.018103|
|2022.01.01|2024-05-18 00:15:00|0.018038|
|2022.01.01|2024-05-18 00:30:00| 0.01801|
|2022.01.01|2024-05-18 00:45:00|0.018095|
|2022.01.01|2024-05-18 01:00:00|0.018187|
|2022.01.01|2024-05-18 01:15:00|0.018158|
|2022.01.01|2024-05-18 01:30:00|0.018087|
|2022.01.01|2024-05-18 01:45:00|0.018103|
|2022.01.01|2024-05-18 02:00:00|0.018172|
|2022.01.01|2024-05-18 02:15:00|0.018167|
|2022.01.01|2024-05-18 02:30:00|0.018129|
|2022.01.01|2024-05-18 02:45:00|0.018056|
|2022.01.01|2024-05-18 03:00:00|0.017923|
|2022.01.01|2024-05-18 03:15:00|0.017764|
|2022.01.01|2024-05-18 03:30:00|0.017725|
|2022.01.01|2024-05-18 03:45:00| 0.01777|
|2022.01.01|2024-05-18 04:00:00|0.017912|
|2022.01.01|2024-05-18 04:15:00|0.018011|
|2022.01.01|2024-05-18 04:30:00| 0.01817|
|2022.01.01|2024-05-18 04:45:00| 0.01846|
+----------+-------------------+--------+
only showing top 20 rows

+----------------+--------------+
|            time|production_(W)|
+----------------+--------------+
|01.01.2022 00:00|           0.0|
|01.01.2022 00:15|           0.0|
|01.01.2022 00:30|           0.0|
|01.01.2022 00:45|           0.0|
|01.01.2022 01:00|           0.0|
|01.01.2022 01:15|           0.0|
|01.01.2022 01:30|           0.0|
|01.01.2022 01:45|           0.0|
|01.01.2022 02:00|           0.0|
|01.01.2022 02:15|           0.0|
|01.01.2022 02:30|           0.0|
|01.01.2022 02:45|           0.0|
|01.01.2022 03:00|           0.0|
|01.01.2022 03:15|           0.0|
|01.01.2022 03:30|           0.0|
|01.01.2022 03:45|           0.0|
|01.01.2022 04:00|           0.0|
|01.01.2022 04:15|           0.0|
|01.01.2022 04:30|           0.0|
|01.01.2022 04:45|           0.0|
|01.01.2022 05:00|           0.0|
|01.01.2022 05:15|           0.0|
|01.01.2022 05:30|           0.0|
|01.01.2022 05:45|           0.0|
|01.01.2022 06:00|           0.0|
|01.01.2022 06:15|           0.0|
|01.01.2022 06:30|           0.0|
|01.01.2022 06:45|           0.0|
|01.01.2022 07:00|           0.0|
|01.01.2022 07:15|           0.0|
|01.01.2022 07:30|       12.3333|
|01.01.2022 07:45|          76.0|
|01.01.2022 08:00|         221.0|
|01.01.2022 08:15|      397.3333|
|01.01.2022 08:30|      346.3333|
|01.01.2022 08:45|        1237.0|
|01.01.2022 09:00|        2377.0|
|01.01.2022 09:15|     3353.6667|
|01.01.2022 09:30|        2365.0|
|01.01.2022 09:45|     2024.3334|
|01.01.2022 10:00|     4235.3335|
|01.01.2022 10:15|     1580.6666|
|01.01.2022 10:30|     2167.3333|
|01.01.2022 10:45|     2420.3333|
|01.01.2022 11:00|     1419.3334|
|01.01.2022 11:15|     1229.3334|
|01.01.2022 11:30|     1585.3334|
|01.01.2022 11:45|     5199.6665|
|01.01.2022 12:00|     1966.6666|
|01.01.2022 12:15|        1629.0|
|01.01.2022 12:30|     1318.3334|
|01.01.2022 12:45|     1396.3334|
|01.01.2022 13:00|     1205.6666|
|01.01.2022 13:15|      594.3333|
|01.01.2022 13:30|      239.3333|
|01.01.2022 13:45|      360.3333|
|01.01.2022 14:00|      247.6667|
|01.01.2022 14:15|      170.6667|
|01.01.2022 14:30|      135.6667|
|01.01.2022 14:45|      116.6667|
|01.01.2022 15:00|       76.6667|
|01.01.2022 15:15|        7.6667|
|01.01.2022 15:30|           8.0|
|01.01.2022 15:45|           0.0|
|01.01.2022 16:00|           0.0|
|01.01.2022 16:15|           0.0|
|01.01.2022 16:30|           0.0|
|01.01.2022 16:45|           0.0|
|01.01.2022 17:00|           0.0|
|01.01.2022 17:15|           0.0|
|01.01.2022 17:30|           0.0|
|01.01.2022 17:45|           0.0|
|01.01.2022 18:00|           0.0|
|01.01.2022 18:15|           0.0|
|01.01.2022 18:30|           0.0|
|01.01.2022 18:45|           0.0|
|01.01.2022 19:00|           0.0|
|01.01.2022 19:15|           0.0|
|01.01.2022 19:30|           0.0|
|01.01.2022 19:45|           0.0|
|01.01.2022 20:00|           0.0|
|01.01.2022 20:15|           0.0|
|01.01.2022 20:30|           0.0|
|01.01.2022 20:45|           0.0|
|01.01.2022 21:00|           0.0|
|01.01.2022 21:15|           0.0|
|01.01.2022 21:30|           0.0|
|01.01.2022 21:45|           0.0|
|01.01.2022 22:00|           0.0|
|01.01.2022 22:15|           0.0|
|01.01.2022 22:30|           0.0|
|01.01.2022 22:45|           0.0|
|01.01.2022 23:00|           0.0|
|01.01.2022 23:15|           0.0|
|01.01.2022 23:30|           0.0|
|01.01.2022 23:45|           0.0|
|02.01.2022 00:00|           0.0|
|02.01.2022 00:15|           0.0|
|02.01.2022 00:30|           0.0|
|02.01.2022 00:45|           0.0|
+----------------+--------------+
only showing top 100 rows

+------------+-----+----------------+
|Delivery day|Hours|Prices (EUR/MWh)|
+------------+-----+----------------+
|  01.01.2022|   H1|           61.84|
|  01.01.2022|   H2|           41.33|
|  01.01.2022|   H3|           43.22|
|  01.01.2022|   H4|           45.46|
|  01.01.2022|   H5|           37.67|
|  01.01.2022|   H6|            39.7|
|  01.01.2022|   H7|           40.59|
|  01.01.2022|   H8|           43.26|
|  01.01.2022|   H9|           49.66|
|  01.01.2022|  H10|           70.05|
|  01.01.2022|  H11|           76.79|
|  01.01.2022|  H12|            84.1|
|  01.01.2022|  H13|           94.74|
|  01.01.2022|  H14|            96.8|
|  01.01.2022|  H15|           97.17|
|  01.01.2022|  H16|           101.0|
|  01.01.2022|  H17|           126.6|
|  01.01.2022|  H18|          149.97|
|  01.01.2022|  H19|          146.33|
|  01.01.2022|  H20|          140.28|
+------------+-----+----------------+
only showing top 20 rows

In [29]:
production = production.withColumn("time",to_timestamp(col("time"),"dd.MM.yyyy HH:mm"))\
                       .withColumn("utc_time",to_utc_timestamp(col("time"),"Europe/Budapest"))\
                       .withColumn("rownum", monotonically_increasing_id())

DataFrame[time: timestamp, production_(W): double, utc_time: timestamp, rownum: bigint]

In [36]:
production.filter(col("time") >= "2022-10-30").show(50)

+-------------------+--------------+-------------------+------+
|               time|production_(W)|           utc_time|rownum|
+-------------------+--------------+-------------------+------+
|2022-10-30 00:00:00|           0.0|2022-10-29 22:00:00| 28992|
|2022-10-30 00:15:00|           0.0|2022-10-29 22:15:00| 28993|
|2022-10-30 00:30:00|           0.0|2022-10-29 22:30:00| 28994|
|2022-10-30 00:45:00|           0.0|2022-10-29 22:45:00| 28995|
|2022-10-30 01:00:00|           0.0|2022-10-29 23:00:00| 28996|
|2022-10-30 01:15:00|           0.0|2022-10-29 23:15:00| 28997|
|2022-10-30 01:30:00|           0.0|2022-10-29 23:30:00| 28998|
|2022-10-30 01:45:00|           0.0|2022-10-29 23:45:00| 28999|
|2022-10-30 02:00:00|           0.0|2022-10-30 00:00:00| 29000|
|2022-10-30 02:15:00|           0.0|2022-10-30 00:15:00| 29001|
|2022-10-30 02:30:00|           0.0|2022-10-30 00:30:00| 29002|
|2022-10-30 02:45:00|           0.0|2022-10-30 00:45:00| 29003|
|2022-10-30 03:00:00|           0.0|2022-10-30 02:00:00| 29004|
|2022-10-30 03:15:00|           0.0|2022-10-30 02:15:00| 29005|
|2022-10-30 03:30:00|           0.0|2022-10-30 02:30:00| 29006|
|2022-10-30 03:45:00|           0.0|2022-10-30 02:45:00| 29007|
|2022-10-30 04:00:00|           0.0|2022-10-30 03:00:00| 29008|
|2022-10-30 04:15:00|           0.0|2022-10-30 03:15:00| 29009|
|2022-10-30 04:30:00|           0.0|2022-10-30 03:30:00| 29010|
|2022-10-30 04:45:00|           0.0|2022-10-30 03:45:00| 29011|
|2022-10-30 05:00:00|           0.0|2022-10-30 04:00:00| 29012|
|2022-10-30 05:15:00|           0.0|2022-10-30 04:15:00| 29013|
|2022-10-30 05:30:00|           0.0|2022-10-30 04:30:00| 29014|
|2022-10-30 05:45:00|           0.0|2022-10-30 04:45:00| 29015|
|2022-10-30 06:00:00|           0.0|2022-10-30 05:00:00| 29016|
|2022-10-30 06:15:00|           0.0|2022-10-30 05:15:00| 29017|
|2022-10-30 06:30:00|           0.0|2022-10-30 05:30:00| 29018|
|2022-10-30 06:45:00|       43.6667|2022-10-30 05:45:00| 29019|
|2022-10-30 07:00:00|       84.6667|2022-10-30 06:00:00| 29020|
|2022-10-30 07:15:00|      140.3333|2022-10-30 06:15:00| 29021|
|2022-10-30 07:30:00|      171.3333|2022-10-30 06:30:00| 29022|
|2022-10-30 07:45:00|         196.0|2022-10-30 06:45:00| 29023|
|2022-10-30 08:00:00|         247.0|2022-10-30 07:00:00| 29024|
|2022-10-30 08:15:00|      325.6667|2022-10-30 07:15:00| 29025|
|2022-10-30 08:30:00|      345.6667|2022-10-30 07:30:00| 29026|
|2022-10-30 08:45:00|         480.0|2022-10-30 07:45:00| 29027|
|2022-10-30 09:00:00|      550.3333|2022-10-30 08:00:00| 29028|
|2022-10-30 09:15:00|         555.0|2022-10-30 08:15:00| 29029|
|2022-10-30 09:30:00|         702.0|2022-10-30 08:30:00| 29030|
|2022-10-30 09:45:00|         716.0|2022-10-30 08:45:00| 29031|
|2022-10-30 10:00:00|      778.6667|2022-10-30 09:00:00| 29032|
|2022-10-30 10:15:00|         771.0|2022-10-30 09:15:00| 29033|
|2022-10-30 10:30:00|      969.3333|2022-10-30 09:30:00| 29034|
|2022-10-30 10:45:00|        1182.0|2022-10-30 09:45:00| 29035|
|2022-10-30 11:00:00|     1114.3334|2022-10-30 10:00:00| 29036|
|2022-10-30 11:15:00|     1357.3334|2022-10-30 10:15:00| 29037|
|2022-10-30 11:30:00|        1427.0|2022-10-30 10:30:00| 29038|
|2022-10-30 11:45:00|     1339.3334|2022-10-30 10:45:00| 29039|
|2022-10-30 12:00:00|        1458.0|2022-10-30 11:00:00| 29040|
|2022-10-30 12:15:00|        1371.0|2022-10-30 11:15:00| 29041|
+-------------------+--------------+-------------------+------+
only showing top 50 rows

In [34]:
filter = production.groupBy("utc_time").agg(count("time").alias("count")).filter(col("count")> 1)

filtered = production.join(filter,"utc_time").select("time","utc_time","rownum")
filtered.show()

+-------------------+-------------------+------+
|               time|           utc_time|rownum|
+-------------------+-------------------+------+
|2022-03-27 03:00:00|2022-03-27 01:00:00|  8168|
|2022-03-27 03:15:00|2022-03-27 01:15:00|  8169|
|2022-03-27 03:30:00|2022-03-27 01:30:00|  8170|
|2022-03-27 03:45:00|2022-03-27 01:45:00|  8171|
|2022-03-27 03:00:00|2022-03-27 01:00:00|  8172|
|2022-03-27 03:15:00|2022-03-27 01:15:00|  8173|
|2022-03-27 03:30:00|2022-03-27 01:30:00|  8174|
|2022-03-27 03:45:00|2022-03-27 01:45:00|  8175|
|2022-03-27 04:00:00|2022-03-27 03:00:00|  8176|
|2022-03-27 04:15:00|2022-03-27 03:15:00|  8177|
|2022-03-27 04:30:00|2022-03-27 03:30:00|  8178|
|2022-03-27 04:45:00|2022-03-27 03:45:00|  8179|
|2022-03-27 05:00:00|2022-03-27 03:00:00|  8180|
|2022-03-27 05:15:00|2022-03-27 03:15:00|  8181|
|2022-03-27 05:30:00|2022-03-27 03:30:00|  8182|
|2022-03-27 05:45:00|2022-03-27 03:45:00|  8183|
|2023-03-26 03:00:00|2023-03-26 01:00:00| 43112|
|2023-03-26 03:15:00|2023-03-26 01:15:00| 43113|
|2023-03-26 03:30:00|2023-03-26 01:30:00| 43114|
|2023-03-26 03:45:00|2023-03-26 01:45:00| 43115|
+-------------------+-------------------+------+
only showing top 20 rows

# Transzformálás

In [ ]:
df = df.withColumn("timestamp", to_timestamp(col("timestamp"), "dd.MM.yyyy HH:mm"))
#df.printSchema()
#df.show()

# Betöltés

In [ ]:
#inserting data into DB
df.write\
  .format("jdbc")\
  .mode("append")\
  .option("driver","com.mysql.jdbc.Driver")\
  .option("url", "jdbc:mysql://localhost:3306/energycom")\
  .option("dbtable", "consumer_profile")\
  .option("user", "root")\
  .option("password", "mysql")\
  .save()

# Adatok beolvasása az adatbázisból

In [2]:
# Adatok betöltése a MySQL adatbázisból
consumer = spark.read \
    .format("jdbc") \
    .option("url", mysql_url) \
    .option("driver", "com.mysql.cj.jdbc.Driver")\
    .option("dbtable", "consumer_profile") \
    .load()

production = spark.read \
    .format("jdbc") \
    .option("url", mysql_url) \
    .option("driver", "com.mysql.cj.jdbc.Driver")\
    .option("dbtable", "solar_panel_production") \
    .load()

price = spark.read \
    .format("jdbc") \
    .option("url", mysql_url) \
    .option("driver", "com.mysql.cj.jdbc.Driver")\
    .option("dbtable", "hupx_energy_price") \
    .load()

consumer.show(10)
production.show(10)
price.show(10)

+----------+-------------------+---------------+
|profile_id|          timestamp|consumption_kwh|
+----------+-------------------+---------------+
|         1|2023-01-01 00:00:00|        0.02656|
|         1|2023-01-01 00:15:00|        0.02601|
|         1|2023-01-01 00:30:00|        0.02552|
|         1|2023-01-01 00:45:00|        0.02483|
|         1|2023-01-01 01:00:00|        0.02421|
|         1|2023-01-01 01:15:00|        0.02367|
|         1|2023-01-01 01:30:00|        0.02321|
|         1|2023-01-01 01:45:00|        0.02281|
|         1|2023-01-01 02:00:00|        0.02246|
|         1|2023-01-01 02:15:00|        0.02214|
+----------+-------------------+---------------+
only showing top 10 rows

+---------+-------------------+--------------+
|device_id|          timestamp|production_kwh|
+---------+-------------------+--------------+
|        1|2023-01-01 00:00:00|       0.00000|
|        1|2023-01-01 00:15:00|       0.00000|
|        1|2023-01-01 00:30:00|       0.00000|
|        1|2023-01-01 00:45:00|       0.00000|
|        1|2023-01-01 01:00:00|       0.00000|
|        1|2023-01-01 01:15:00|       0.00000|
|        1|2023-01-01 01:30:00|       0.00000|
|        1|2023-01-01 01:45:00|       0.00000|
|        1|2023-01-01 02:00:00|       0.00000|
|        1|2023-01-01 02:15:00|       0.00000|
+---------+-------------------+--------------+
only showing top 10 rows

+-------------------+-----------------+
|          timestamp|price_eur_per_mwh|
+-------------------+-----------------+
|2023-01-01 00:00:00|         19.76000|
|2023-01-01 00:15:00|         19.76000|
|2023-01-01 00:30:00|         19.76000|
|2023-01-01 00:45:00|         19.76000|
|2023-01-01 01:00:00|          0.19000|
|2023-01-01 01:15:00|          0.19000|
|2023-01-01 01:30:00|          0.19000|
|2023-01-01 01:45:00|          0.19000|
|2023-01-01 02:00:00|          0.07000|
|2023-01-01 02:15:00|          0.07000|
+-------------------+-----------------+
only showing top 10 rows

# Kiindulási adatok egyesítése

Az optimalizáció előkészítéséhez egyesítjük az adatokat egyetlen Pandas DataFrame-ben.

Előzetes szűrés szükséges a fogyasztó rendszer és a termelő egységre, az adatbázisban több egység termelési illetve fogyasztási adatait is tárolhatjuk. A szűrést azonosítók segítségével tehetjük meg.
Egységesség érdekében float típusú mezővé alakítom a három mutatót a számítási feladatok érdekében.

Itt kerülnek létrehozásra az általánosan szükséges paraméterek is, mint például a rendelkezésre álló akkumulátor kapacitása is.

In [4]:
from pyspark.sql.functions import *
# paramaméterek
capacity = 10 #kwh

# szűrés
consumer   = consumer.filter(col("profile_id") == 1)
production = production.filter(col("device_id") == 1)

# összekapcsolás
process = consumer.select("timestamp","consumption_kwh").join(production.select("timestamp","production_kwh"),"timestamp","inner")\
                  .join(price.select("timestamp","price_eur_per_mwh"),"timestamp","inner")

#rendezés join után és cast-olás
process = process.orderBy("timestamp")\
                 .withColumn("consumption_kwh", process["consumption_kwh"].cast("float"))\
                 .withColumn("production_kwh", process["production_kwh"].cast("float"))\
                 .withColumn("price_eur_per_mwh", process["price_eur_per_mwh"].cast("float"))\
                 .toPandas()
process.head()

            timestamp  consumption_kwh  production_kwh  price_eur_per_mwh
0 2023-01-01 00:00:00          0.02656             0.0              19.76
1 2023-01-01 00:15:00          0.02601             0.0              19.76
2 2023-01-01 00:30:00          0.02552             0.0              19.76
3 2023-01-01 00:45:00          0.02483             0.0              19.76
4 2023-01-01 01:00:00          0.02421             0.0               0.19

# Optimalizálási feladat

Most, hogy kész a rendezett adatsorunk, alkalmazhatjuk a különböző optimalizációs stratégiákat a minél eredményesebb energia gazdálkodás érdekében. 

A célfüggvény amit választottunk az a fogyasztási igények kiszolgálása a **költség minimalizálásával**. Annál jobb az eredmény, minél kevesebbe került az energiaszolgáltatás az adott időszakra.

különböző megvalósításokat igyekszünk összehasonlítani, hogy megállapíthassuk, melyik megoldás a legkedvezőbb.

# Egyszerű stratégia

A következő blokkokban egy próba algoritmust implementáltam, mely nem az adatok viszonya alapján készíti el a költség tervet.

Csupán referenciaként szolgáló megoldás.

**Működés:**

Ha az adott időben a termelés fedezi a fogyasztást, akkor többlet keletkezik, a többletből betáplálunk annyit az akkumulátorba, amennyi belefér, az el nem tárolható mennyiséget pedig kitápláljuk a hálózatra.

Másik esetben, mikor nem fedezi a termelés a fogyasztást, akkor a szükséges energiamennyiséget első sorban az akkumulátorban tárolt energiából pótoljuk, hogyha az sem elég, akkor vételezünk a hálózatról.

In [6]:
import numpy as np
# energia többlet és igény kiszámítása a termelés és fogyasztás különbségéből,
# valamint töltöttséget követő oszlopok bevezetése a negyedóra elejére és végére, alapértelmezett értékadás.
basic_p = process.assign(energy_to_store = lambda x: np.where(x['production_kwh'] - x['consumption_kwh'] > 0, x['production_kwh'] - x['consumption_kwh'], 0),
                       energy_to_get   = lambda x: np.where(x['consumption_kwh'] - x['production_kwh'] > 0, x['consumption_kwh'] - x['production_kwh'], 0),
                       battery_charge_start = float(0.00000),
                       battery_charge_end   = float(0.00000))
basic_p.head()

#from pyspark.sql.functions import when
#basic_p = process.withColumn("energy_to_store", when(col("production_kwh")-col("consumption_kwh")>0,col("production_kwh")-col("consumption_kwh"))\
#                          .otherwise(0))\
#               .withColumn("energy_to_get",when(col("consumption_kwh")-col("production_kwh")>0,col("consumption_kwh")-col("production_kwh"))\
#                          .otherwise(0))\
#               .withColumn("battery_charge_at_start",lit(0.00000))\
#               .withColumn("battery_charge_at_end",lit(0.00000))

# kezdő értéket állíthatunk az akkumulátorunknak a vizsgált időszak elején.
# basic_p.at[0,"battery_charge_start"] = 2

#ha tárolni kell akkor mennyit tudunk eltárolni
if basic_p.at[0,'energy_to_store'] > 0:
        temp = basic_p.at[0,'battery_charge_start'] + basic_p.at[0,'energy_to_store']
        if temp <= capacity:
            basic_p.at[0,'battery_charge_end'] = temp
        else:
            basic_p.at[0,'battery_charge_end'] = capacity
            
#ha be kell szerezni, mennyit tudunk szolgáltatni saját tárunkból
else:
        temp = basic_p.at[0,'battery_charge_start'] - basic_p.at[0,'energy_to_get']
        if temp > 0:
            basic_p.at[0,'battery_charge_end'] = temp
        else:
            basic_p.at[0,'battery_charge_end'] = 0

for i in range(1,int(basic_p.size/8)):
    basic_p.at[i,'battery_charge_start'] = basic_p.at[i-1,'battery_charge_end']
    if basic_p.at[i,'energy_to_store'] > 0:
        temp = basic_p.at[i,'battery_charge_start'] + basic_p.at[i,'energy_to_store']
        if temp <= capacity:
            basic_p.at[i,'battery_charge_end'] = temp
        else:
            basic_p.at[i,'battery_charge_end'] = capacity
    else:
        temp = basic_p.at[i,'battery_charge_start'] - basic_p.at[i,'energy_to_get']
        if temp > 0:
            basic_p.at[i,'battery_charge_end'] = temp
        else:
            basic_p.at[i,'battery_charge_end'] = 0
#basic_p.tail(10)

#az előző adatok alapján megállapítani, hogy mennyit fogyasztunk saját, illetve hálózati energiából, 
# valamint mennyi energiát táplálunk be saját akkumulátorunkba, vagy a hálózatba. 
basic_p = basic_p.assign(taking_from_battery = lambda x: np.where(x['battery_charge_start'] - x['battery_charge_end'] > 0, x['battery_charge_start'] - x['battery_charge_end'], 0),
                       feeding_battery   = lambda x: np.where(x['battery_charge_end'] - x['battery_charge_start'] > 0, x['battery_charge_end'] - x['battery_charge_start'], 0),
                       taking_from_grid  = lambda x: x['energy_to_get']-x['taking_from_battery'],
                       feeding_grid      = lambda x: x['energy_to_store']-x['feeding_battery'],
                       price             = lambda x: (x['taking_from_grid']*x['price_eur_per_mwh']-x['feeding_grid']*x['price_eur_per_mwh'])*0.001) # mwh-->kwh konverzió

basic_p.tail()

,timestamp,consumption_kwh,production_kwh,price_eur_per_mwh,energy_to_store,energy_to_get,battery_charge_start,battery_charge_end,taking_from_battery,feeding_battery,taking_from_grid,feeding_grid,price
2971,2023-01-31 22:45:00,0.03004,0.0,121.650002,0.0,0.03004,8.86815,8.83811,0.03004,0.0,0.0,0.0,0.0
2972,2023-01-31 23:00:00,0.02862,0.0,98.690002,0.0,0.02862,8.83811,8.80949,0.02862,0.0,0.0,0.0,0.0
2973,2023-01-31 23:15:00,0.02734,0.0,98.690002,0.0,0.02734,8.80949,8.78215,0.02734,0.0,0.0,0.0,0.0
2974,2023-01-31 23:30:00,0.02614,0.0,98.690002,0.0,0.02614,8.78215,8.75601,0.02614,0.0,0.0,0.0,0.0
2975,2023-01-31 23:45:00,0.02507,0.0,98.690002,0.0,0.02507,8.75601,8.73094,0.02507,0.0,0.0,0.0,0.0